In [ ]:
!pip install tensorflow==2.12.0


INFO: pip is looking at multiple versions of jax to determine which version is compatible with other requirements. This could take a while.
INFO: pip is still looking at multiple versions of jax to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 586.0/586.0 MB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 94.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 84.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 106.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 31.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 123.3 MB/s eta 0:00:00

In [ ]:
!pip install tensorflow==2.12.0


In [ ]:
import tensorflow as tf
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))


Num GPUs Available: 0


In [ ]:
!python --version


Python 3.11.13


In [17]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [36]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [37]:
#### sentences
#sent=[  'the glass of milk',
#     'the glass of juice',
#     'the cup of tea',
#    'I am a good boy',
#     'I am a good developer',
#     'understand the meaning of words',
#     'your videos are good']
#
sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [38]:
sent


['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [39]:
### Vocabulary size
voc_size=500

In [40]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[354, 222, 50, 383, 352, 373], [42, 236, 50, 84, 411, 213], [47, 84, 123, 403], [354, 319, 50, 362, 354, 254], [250, 421, 421, 50, 84, 411, 213], [244, 50, 84, 411, 210, 100]]


In [41]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [42]:
#making lenth of each sentences equal
sent_length=8
embedded_docs=tf.keras.preprocessing.sequence.pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0 354 222  50 383 352 373]
 [  0   0  42 236  50  84 411 213]
 [  0   0   0   0  47  84 123 403]
 [  0   0 354 319  50 362 354 254]
 [  0 250 421 421  50  84 411 213]
 [  0   0 244  50  84 411 210 100]]


In [43]:
#model=Sequential()
#model.add(Embedding(voc_size,10,))
#model.compile('adam','mse')

model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=10))  # removed input_length
model.build(input_shape=(None, sent_length))  # explicitly build the model

model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [44]:
##'The world is a better place',
embedded_docs[0]

array([  0,   0, 354, 222,  50, 383, 352, 373], dtype=int32)

In [45]:
# Reshape the input to add a batch dimension
model.predict(embedded_docs[0][None, :])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


array([[[-0.00407786,  0.0374324 ,  0.01410678,  0.03592031,
          0.03471902, -0.03679609,  0.03396443, -0.01280658,
          0.00216274,  0.01745694],
        [-0.00407786,  0.0374324 ,  0.01410678,  0.03592031,
          0.03471902, -0.03679609,  0.03396443, -0.01280658,
          0.00216274,  0.01745694],
        [ 0.00342324,  0.02916045, -0.02306679,  0.02628603,
         -0.04833385, -0.03164542,  0.02214683, -0.04706607,
         -0.0021373 , -0.03814516],
        [-0.01677804, -0.02612569,  0.02683182, -0.03201296,
         -0.0202788 ,  0.04545344,  0.03363475, -0.04728463,
          0.04730208,  0.02262459],
        [-0.03399955,  0.03658383, -0.04399241, -0.02593731,
         -0.0124058 , -0.03529193,  0.03463492,  0.04951611,
          0.03743645, -0.04879808],
        [ 0.01491452,  0.02022353,  0.03527105,  0.01158279,
         -0.02178766, -0.01258149, -0.02015967, -0.02872286,
         -0.0084951 ,  0.00360367],
        [ 0.03516677, -0.03347367,  0.03997201,  0.0

In [46]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step
[[[-0.00407786  0.0374324   0.01410678  0.03592031  0.03471902
   -0.03679609  0.03396443 -0.01280658  0.00216274  0.01745694]
  [-0.00407786  0.0374324   0.01410678  0.03592031  0.03471902
   -0.03679609  0.03396443 -0.01280658  0.00216274  0.01745694]
  [ 0.00342324  0.02916045 -0.02306679  0.02628603 -0.04833385
   -0.03164542  0.02214683 -0.04706607 -0.0021373  -0.03814516]
  [-0.01677804 -0.02612569  0.02683182 -0.03201296 -0.0202788
    0.04545344  0.03363475 -0.04728463  0.04730208  0.02262459]
  [-0.03399955  0.03658383 -0.04399241 -0.02593731 -0.0124058
   -0.03529193  0.03463492  0.04951611  0.03743645 -0.04879808]
  [ 0.01491452  0.02022353  0.03527105  0.01158279 -0.02178766
   -0.01258149 -0.02015967 -0.02872286 -0.0084951   0.00360367]
  [ 0.03516677 -0.03347367  0.03997201  0.04128659 -0.02689202
    0.0305602  -0.00831324  0.03309113  0.00501724  0.03088785]
  [ 0.02375447  0.03757444 -0.00438414 -0.01361629 -0.02140193
   -0.01583